spring:
  application:
    name: gateway-service

server:
  port: 8765
  
zuul:
  prefix: /api
  routes: 
    bookrack: 
      path: /bookrack/**
      serviceId: book-rack-service
    book: 
      path: /book/**
      serviceId: book-service          

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false